#' @title Save Report as CSV and HTML
#'
#' @description
#' Save a data frame of article metadata as both a CSV file and an HTML file with a markdown-styled table.
#' Options are provided to control file format outputs and verbosity.
#'
#' @usage
#' save_report(input, filename, save_csv, save_html, title, cols, width, verbose = TRUE)
#'
#' @param input A data frame containing article data (e.g., "title", "summary", "url").
#' @param filename A character string specifying the base filename (without extension).
#' @param save_csv Logical. Save output as a CSV file? Default is TRUE.
#' @param save_html Logical. Save output as an HTML file? Default is TRUE.
#' @param title A character string specifying the HTML page title. Default is "Article Summary Report".
#' @param cols A character vector of column names to include in the output. Default is c("title", "summary").
#' @param width A numeric vector of column widths for the HTML table. Default is c(1, 3).
#' @param verbose Logical. Should messages be printed? Default is TRUE.
#'
#' @return
#' Files are written to disk in the specified formats. The function returns (invisibly) a list of saved file paths.
#'
#' @details
#' A timestamp is appended to the base filename to uniquely identify each output.
#' If both save_csv and save_html are FALSE, no files are saved and a message is issued (if verbose = TRUE).
#'
#' @examples
#' \dontrun{
#' papers <- get_articles(journal = "Nature Medicine")
#' papers_with_summary <- add_summary(papers)
#' save_report(papers_with_summary, "Summary", save_csv = TRUE, save_html = TRUE)
#' }
#'
#' @importFrom dplyr select all_of
#' @importFrom readr write_csv
#' @importFrom tinytable save_tt
#' @importFrom tools file_path_sans_ext
#' @export
#' @keywords file export, markdown, HTML, CSV

save_report <- function(input, filename,
                        save_csv = TRUE,
                        save_html = TRUE,
                        title = "Article Summary Report",
                        cols = c("title", "summary"),
                        width = c(1, 3),
                        verbose = TRUE) {

  if (!inherits(input, "data.frame")) stop("input must be a data frame.")

  missing_cols <- setdiff(cols, names(input))
  if (length(missing_cols) > 0) {
    stop("The following columns are missing in input: ", paste(missing_cols, collapse = ", "))
  }

  if (!save_csv && !save_html) {
    if (verbose) message("No output saved: both save_csv and save_html are FALSE.")
    return(invisible(NULL))
  }

  filename <- tools::file_path_sans_ext(filename)
  timestamp <- format(Sys.time(), "%Y%m%d")
  filename <- paste0(filename, "_", timestamp)
  csv_file <- paste0(filename, ".csv")
  html_file <- paste0(filename, ".html")

  now <- Sys.time()
  date_str <- format(now, "%B %d, %Y")
  time_str <- format(now, "%H:%M:%S")
  journal_name <- if ("source" %in% names(input)) paste(unique(input$source), collapse = ", ") else "Unknown"

  saved_files <- list()

  if (save_csv) {
    readr::write_csv(input |> dplyr::select(dplyr::all_of(cols)), csv_file)
    if (verbose) message("CSV saved to: ", csv_file)
    saved_files$csv <- csv_file
  }

  if (save_html) {
    tt_obj <- tt_article(input, cols = cols, width = width)

    html_header <- sprintf(
      "<html>
  <head>
    <meta charset='UTF-8'>
    <title>%s</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 20px; }
      h1 { text-align: center; margin-bottom: 10px; }
      p.date { text-align: center; font-size: 16px; margin-bottom: 20px; font-weight: bold; }
      h2 { font-size: 20px; margin-top: 30px; font-weight: bold; }
      ul { margin-top: 10px; }
      ul li { font-size: 16px; }
      .spacer { margin-top: 40px; }
      table { width: 100%%; border-collapse: collapse; margin-top: 20px; }
      th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
      th { background-color: #f2f2f2; }
    </style>
  </head>
  <body>
    <h1>%s</h1>
    <p class='date'>%s</p>
    <h2>Report Information</h2>
    <ul>
      <li><strong>Generated by:</strong> NatChat v1.0.1</li>
      <li><strong>Date:</strong> %s</li>
      <li><strong>Time:</strong> %s</li>
      <li><strong>Journal:</strong> %s</li>
      <li><strong>Model:</strong> llama3.2</li>
    </ul>
    <div class='spacer'></div>
    <h2>Articles Summary</h2>",
      title, title, date_str, date_str, time_str, journal_name
    )

    tinytable::save_tt(tt_obj, output = html_file, overwrite = TRUE)
    html_content <- readLines(html_file)
    writeLines(c(html_header, html_content[-(1:6)]), html_file)

    if (verbose) message("HTML saved to: ", html_file)
    saved_files$html <- html_file
  }

  invisible(saved_files)
}
