#' @title Save Report as CSV and HTML
#'
#' @description
#' Save a data frame of article metadata as both a CSV file and an HTML file with a markdown-styled table.
#' Options are provided to control file format outputs and verbosity.
#'
#' @usage
#' save_report(input, filename, save_csv, save_html, title, cols, width, verbose, outdir)
#'
#' @param input A data frame containing article data (e.g., "title", "summary", "url").
#' @param filename A character string specifying the base filename (without extension).
#' @param save_csv Logical. Save output as a CSV file? Default is TRUE.
#' @param save_html Logical. Save output as an HTML file? Default is TRUE.
#' @param title A character string specifying the HTML page title. Default is "Article Summary Report".
#' @param cols A character vector of column names to include in the output. Default is c("title", "summary").
#' @param width A numeric vector of column widths for the HTML table. Default is c(1, 3).
#' @param verbose Logical. Should messages be printed? Default is TRUE.
#' @param outdir A character string specifying the directory to save files. Default is current working directory ".".
#'
#' @return
#' Files are written to disk in the specified formats. The function returns (invisibly) a list of saved file paths.
#'
#' @details
#' A timestamp is appended to the base filename to uniquely identify each output.
#' If both save_csv and save_html are FALSE, no files are saved and a message is issued (if verbose = TRUE).
#'
#' @examples
#' \dontrun{
#' papers <- get_articles(journal = "Nature Medicine")
#' papers_with_summary <- add_summary(papers)
#' save_report(papers_with_summary, save_csv = TRUE, save_html = TRUE)
#' }
#'
#' @importFrom dplyr select all_of
#' @importFrom readr write_csv
#' @importFrom tinytable save_tt
#' @importFrom tools file_path_sans_ext
#' @export
#' @keywords markdown, HTML, CSV

save_report <- function(input, filename = "natchat_summary",
                        save_csv = TRUE,
                        save_html = TRUE,
                        title = "Article Summary Report",
                        cols = c("title", "summary"),
                        width = c(1, 3),
                        verbose = TRUE,
                        outdir = ".") {

  if (!inherits(input, "data.frame")) stop("input must be a data frame.")

  missing_cols <- setdiff(cols, names(input))
  if (length(missing_cols) > 0) {
    stop("The following columns are missing in input: ", paste(missing_cols, collapse = ", "))
  }

  if (!save_csv && !save_html) {
    if (verbose) message("No output saved: both save_csv and save_html are FALSE.")
    return(invisible(NULL))
  }

  filename <- tools::file_path_sans_ext(filename)
  timestamp <- format(Sys.time(), "%Y%m%d")
  base_filename <- paste0(filename, "_", timestamp)
  csv_file <- file.path(outdir, paste0(base_filename, ".csv"))
  html_file <- file.path(outdir, paste0(base_filename, ".html"))

  now <- Sys.time()
  date_str <- format(now, "%B %d, %Y")
  time_str <- format(now, "%H:%M:%S")
  journal_name <- if ("source" %in% names(input)) paste(unique(input$source), collapse = ", ") else "Unknown"

  saved_files <- list()

  if (save_csv) {
    readr::write_csv(input |> dplyr::select(dplyr::all_of(cols)), csv_file)
    if (verbose) message("CSV saved to: ", csv_file)
    saved_files$csv <- csv_file
  }

  if (save_html) {
    tt_obj <- tt_article(input, cols = cols, width = width)

    html_header <- sprintf(
      "<html>
  <head>
    <meta charset='UTF-8'>
    <title>%s</title>
    <style>
      body { font-family: Arial, sans-serif; padding: 20px; }
      h1 { text-align: center; margin-bottom: 10px; }
      p.date { text-align: center; font-size: 16px; margin-bottom: 20px; font-weight: bold; }
      h2 { font-size: 20px; margin-top: 30px; font-weight: bold; }
      ul { margin-top: 10px; }
      ul li { font-size: 16px; }
      .spacer { margin-top: 40px; }
      table { width: 100%%; border-collapse: collapse; margin-top: 20px; }
      th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
      th { background-color: #f2f2f2; }
    </style>
  </head>
  <body>
    <h1>%s</h1>
    <p class='date'>%s</p>
    <h2>Report Information</h2>
    <ul>
      <li><strong>Generated by:</strong> NatChat v1.0.1</li>
      <li><strong>Date:</strong> %s</li>
      <li><strong>Time:</strong> %s</li>
      <li><strong>Journal:</strong> %s</li>
      <li><strong>Model:</strong> llama3.2</li>
    </ul>
    <div class='spacer'></div>
    <h2>Articles Summary</h2>",
      title, title, date_str, date_str, time_str, journal_name
    )

    tinytable::save_tt(tt_obj, output = html_file, overwrite = TRUE)
    html_content <- readLines(html_file)
    writeLines(c(html_header, html_content[-(1:6)]), html_file)

    if (verbose) message("HTML saved to: ", html_file)
    saved_files$html <- html_file
  }

  invisible(saved_files)
}


#' @title Summarize a Nature Journal Issue
#'
#' @description
#' Retrieve and summarize abstracts from the current issue of a selected Nature Portfolio journal using a local LLM and save the output as CSV and/or HTML.
#'
#' @usage
#' summarize_journal(journal, model, filename, save_csv, save_html, verbose, outdir)
#'
#' @param journal A character string indicating the name of the supported Nature journal (e.g., "Nature Biotechnology").
#' @param model A character string specifying the local Ollama model to use for summarization (e.g., "llama3:instruct").
#' @param filename A character string specifying the base filename for saving the report. Default is "natchat_summary".
#' @param save_csv Logical. Save the results as a CSV file? Default is TRUE.
#' @param save_html Logical. Save the results as an HTML file? Default is TRUE.
#' @param verbose Logical. Should informative messages be printed to the console? Default is TRUE.
#' @param outdir A character string specifying the directory to save output files. Default is current working directory ".".
#'
#' @return
#' Invisibly returns a list of file paths (if saved). Generates summarized article metadata and optionally saves it to disk.
#'
#' @details
#' This function is a convenience wrapper around `get_articles()`, `add_prompt()`, `add_summary()`, and `save_report()`.
#' It scrapes the current issue, summarizes abstracts using a local LLM, and exports the result.
#'
#' @examples
#' \dontrun{
#' summarize_journal(journal = "Nature Medicine", model = "llama3", save_csv = TRUE, save_html = TRUE)
#' }
#'
#' @export
#' @keywords summarization, paper, Nature, export

summarize_journal <- function(journal,
                              model = "llama3.1",
                              filename = "natchat_summary",
                              save_csv = TRUE,
                              save_html = TRUE,
                              verbose = TRUE,
                              outdir = ".") {

  if (verbose) message("Scraping articles from journal: ", journal)
  df <- get_articles(journal, verbose = FALSE)

  if (nrow(df) == 0) {
    stop("No articles found. Please check available journal names by running `nat_journals()` function or try again later.")
  }

  if (verbose) message("Building prompts...")
  df <- add_prompt(df)

  if (verbose) message("Generating summaries using model: ", model)
  df <- add_summary(df, model = model)

  if (verbose) message("Saving report...")
  paths <- save_report(
    input = df,
    filename = filename,
    save_csv = save_csv,
    save_html = save_html,
    verbose = verbose,
    outdir = outdir
  )

  invisible(paths)
}
